name: build

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2

      - name: Install modules
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy build outputs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BMT_SERVER }} # GitHub secret에 저장된 HOST
          username: ${{ secrets.BMT_USERNAME }} # GitHub secret에 저장된 USERNAME
          password: ${{ secrets.BMT_PWD }} # GitHub secret에 저장된 PASSWORD
          port: ${{ secrets.BMT_PORT }} # GitHub secret에 저장된 PORT
          source: "build/*"
          strip_components: 1
          target: /home/nettars/BMT/eyson/build_test

      - name: action-slack
        uses: 8398a7/action-slack@v3.15.1
        with:
          status: ${{ job.status }}
          author_name: Build Result
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # Pick up events even if the job fails or is canceled.
