name: Bump version
on:
  push:
    branches:
      - feature/create-deploy

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_RELEASE }} # if you don't want to set write permissions use a PAT token
        WITH_V: true

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1 
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
